In [1]:
import numpy as np

In [10]:
x = np.array([2,3,4,1]) #1d array
x2d = np.array([[1,2,3],[4,5,6]]) #2d array
print(x)
print(x2d)

[2 3 4 1]
[[1 2 3]
 [4 5 6]]


# Sequential matrix
    - np.arange()
    - np.linspace()

In [11]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [38]:
np.arange(0,12,2).size

6

In [39]:
np.arange(0,12,2).reshape(2,3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [22]:
np.arange(0,10,.2)


array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [23]:
np.arange(0,10,.2).size

50

In [24]:
np.arange(0,10,.2).reshape(5,10)

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8],
       [6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8],
       [8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8]])

In [25]:
np.arange(0,10,.2).reshape(10,5)

array([[0. , 0.2, 0.4, 0.6, 0.8],
       [1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8],
       [3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8],
       [5. , 5.2, 5.4, 5.6, 5.8],
       [6. , 6.2, 6.4, 6.6, 6.8],
       [7. , 7.2, 7.4, 7.6, 7.8],
       [8. , 8.2, 8.4, 8.6, 8.8],
       [9. , 9.2, 9.4, 9.6, 9.8]])

In [30]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [33]:
np.linspace(0,10,6).size

6

In [34]:
np.linspace(0,10,6).reshape(2,3)

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.]])

In [35]:
np.linspace(0,10,6).reshape(3,2)

array([[ 0.,  2.],
       [ 4.,  6.],
       [ 8., 10.]])

# randomized matrix with np.random
    - np.random.rand()
    - np.random.randn() #normal distribution
    - np.random.randint() #random numbers between a given range
    - np.random.uniform() #random float between a given range
    - np.random.permutation() #random permutation

In [36]:
print(np.random.rand(4,4))

[[0.035299   0.44420173 0.47333046 0.03057953]
 [0.71033889 0.15888404 0.89452115 0.65100349]
 [0.30067109 0.99154054 0.76237037 0.75777021]
 [0.55136771 0.50370144 0.73862631 0.22597787]]


In [37]:
print(np.random.randn(4,4))

[[-0.28166756 -1.97652584  0.3324543   1.1880169 ]
 [ 0.42943034  0.96386262 -0.13522185 -0.21608241]
 [-0.59199697 -0.20034138  0.23434708  1.43893951]
 [-0.50255301  0.01252995  1.68395665 -0.97523995]]


In [44]:
print(np.random.randint(-10,10,(4,4)))

[[ -1  -9  -7 -10]
 [ -7   8  -9   9]
 [ -6   6   9  -1]
 [ -3   6  -9  -5]]


In [45]:
print(np.random.uniform(0,2,(3,3)))

[[1.71554088 1.49818038 0.12618758]
 [0.40543233 1.6272858  1.25544306]
 [1.86293078 1.40340844 0.49766649]]


In [47]:
print(np.random.permutation([1,2,3,4,5,6,7,8,9,10]))

[ 8  9  1  2 10  3  7  4  6  5]


In [48]:
np.random.uniform(2,10,(3,3)).astype(int)


array([[2, 9, 8],
       [3, 7, 5],
       [8, 7, 9]])

In [49]:
a = np.random.randint(-10,10,(3,3))
b = np.random.randint(-10,10,(3,3))

In [50]:
print(a)

[[-1  1 -4]
 [ 0  3 -8]
 [ 8 -2  0]]


In [51]:
print(b)

[[ 5  4 -5]
 [ 3  8  0]
 [-3 -6 -5]]


In [55]:
print(a)

[[-1  1 -4]
 [ 0  3 -8]
 [ 8 -2  0]]


In [52]:
print(a*10)

[[-10  10 -40]
 [  0  30 -80]
 [ 80 -20   0]]


In [53]:
print(a+10)

[[ 9 11  6]
 [10 13  2]
 [18  8 10]]


In [54]:
print(a-10)

[[-11  -9 -14]
 [-10  -7 -18]
 [ -2 -12 -10]]


In [56]:
print(a**2)

[[ 1  1 16]
 [ 0  9 64]
 [64  4  0]]


In [57]:
print(a/5)

[[-0.2  0.2 -0.8]
 [ 0.   0.6 -1.6]
 [ 1.6 -0.4  0. ]]


In [58]:
print(a//5)

[[-1  0 -1]
 [ 0  0 -2]
 [ 1 -1  0]]


In [60]:
print(a+b)
print(a-b)
print(a/b)
print(a//b)

[[ 4  5 -9]
 [ 3 11 -8]
 [ 5 -8 -5]]
[[-6 -3  1]
 [-3 -5 -8]
 [11  4  5]]
[[-0.2         0.25        0.8       ]
 [ 0.          0.375             -inf]
 [-2.66666667  0.33333333 -0.        ]]
[[-1  0  0]
 [ 0  0  0]
 [-3  0  0]]


C:\Users\sriva\AppData\Local\Temp\ipykernel_23112\1366849777.py:3: RuntimeWarning: divide by zero encountered in divide
  print(a/b)
C:\Users\sriva\AppData\Local\Temp\ipykernel_23112\1366849777.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(a//b)


In [62]:
print(a*b) #element wise multiplication
print(a@b) #matrix multiplication

[[ -5   4  20]
 [  0  24   0]
 [-24  12   0]]
[[ 10  28  25]
 [ 33  72  40]
 [ 34  16 -40]]


# Matrix multiplication
    - a @ b
    - np.matmul(a,b)
    - np.dot(a,b)